# version: "3.3"

# services:

#   traefik:
#     image: "traefik:v2.5"
#     ports:
#       - 80:80
#       - 443:443
#     restart: always
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock:ro
#       - traefik-public-certificates:/certificates
#     labels:
#       - traefik.enable=true
#       - traefik.http.services.dashboard.loadbalancer.server.port=8080
#       # HTTP
#       - traefik.http.routers.dashboard-http.entrypoints=http
#       - traefik.http.routers.dashboard-http.rule=Host(`traefik.chili-lingerie.com`)
#       # HTTPS
#       - traefik.http.routers.dashboard-https.entrypoints=https
#       - traefik.http.routers.dashboard-https.rule=Host(`traefik.chili-lingerie.com`)
#       - traefik.http.routers.dashboard-https.tls=true
#       - traefik.http.routers.dashboard-https.tls.certresolver=le

#       - traefik.http.routers.dashboard-https.service=api@internal

#       # https-redirect middleware for redirect from HTTP to HTTPS
#       - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
#       - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
#       - traefik.http.routers.dashboard-http.middlewares=https-redirect
#       # BASIC AUTH FOR TRAEFIK
#       - traefik.http.middlewares.admin-auth.basicauth.users=${USERNAME?Variable not set}:${HASHED_PASSWORD?Variable not set}
#       # Add to app-http https-redirect middleware
#       - traefik.http.routers.dashboard-https.middlewares=admin-auth
      
#       # Network
#       - traefik.docker.network=traefik-public
#     command:
#       #- "--log.level=DEBUG"
#       # - --api.insecure=true
#       - --providers.docker
#       - --providers.docker.exposedbydefault=false
#       # HTTP
#       - --entrypoints.http.address=:80
#       # HTTPS
#       - --entrypoints.https.address=:443
#       - --certificatesresolvers.le.acme.email=arturboyun@gmail.com
#       - --certificatesresolvers.le.acme.storage=/certificates/acme.json
#       - --certificatesresolvers.le.acme.tlschallenge=true
#       - --accesslog
#       - --log
#       - --api
#     networks:
#       - traefik-public

# volumes:
#   traefik-public-certificates:

# networks:
#   traefik-public:
#     external: true